initialize_build_layout() {
  local repository_root="$1"
  local build_root_value="${BUILD_ROOT:-build}"

  if [[ "$build_root_value" = /* ]]; then
    BUILD_ROOT_PATH="$build_root_value"
  else
    BUILD_ROOT_PATH="$repository_root/$build_root_value"
  fi

  BUILD_WORK_DIRECTORY="$BUILD_ROOT_PATH/work"
  BUILD_WORK_DERIVED_DATA_PATH="$BUILD_WORK_DIRECTORY/DerivedData"
  BUILD_WORK_RESULTS_DIRECTORY="$BUILD_WORK_DIRECTORY/results"
  BUILD_WORK_TEMP_DIRECTORY="$BUILD_WORK_DIRECTORY/tmp"
  BUILD_WORK_HOME_DIRECTORY="$BUILD_WORK_DIRECTORY/home"

  BUILD_CACHE_DIRECTORY="$BUILD_ROOT_PATH/cache"
  BUILD_CACHE_CLANG_MODULE_DIRECTORY="$BUILD_CACHE_DIRECTORY/clang/ModuleCache"
  BUILD_CACHE_PACKAGE_DIRECTORY="$BUILD_CACHE_DIRECTORY/package"
  BUILD_CACHE_SOURCE_PACKAGES_DIRECTORY="$BUILD_CACHE_DIRECTORY/source_packages"
  BUILD_CACHE_SWIFTPM_CACHE_DIRECTORY="$BUILD_CACHE_DIRECTORY/swiftpm/cache"
  BUILD_CACHE_SWIFTPM_CONFIG_DIRECTORY="$BUILD_CACHE_DIRECTORY/swiftpm/config"

  BUILD_LOGS_DIRECTORY="$BUILD_ROOT_PATH/logs"

  mkdir -p \
    "$BUILD_WORK_DERIVED_DATA_PATH" \
    "$BUILD_WORK_RESULTS_DIRECTORY" \
    "$BUILD_WORK_TEMP_DIRECTORY" \
    "$BUILD_WORK_HOME_DIRECTORY/Library/Caches" \
    "$BUILD_WORK_HOME_DIRECTORY/Library/Developer" \
    "$BUILD_WORK_HOME_DIRECTORY/Library/Logs" \
    "$BUILD_CACHE_CLANG_MODULE_DIRECTORY" \
    "$BUILD_CACHE_PACKAGE_DIRECTORY" \
    "$BUILD_CACHE_SOURCE_PACKAGES_DIRECTORY" \
    "$BUILD_CACHE_SWIFTPM_CACHE_DIRECTORY" \
    "$BUILD_CACHE_SWIFTPM_CONFIG_DIRECTORY" \
    "$BUILD_LOGS_DIRECTORY"
}
